version: '3.8'

services:
  app:
    image: nevereverfelix/my-vite-app:latest  # Replace with your app's image
    ports:
      - "80:80"
    restart: always
    environment:
      - ENV_VAR=example
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
