name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
       
      - name: Debug ESLint Config
        run: npx eslint --print-config src/App.jsx


      - name: Run Linting (Allow Warnings)
        run: npm run lint || echo "Linting completed with warnings"

      - name: Run Tests (Skip if No Tests)
        run: npm test || echo "No tests found, skipping..."

      - name: Build Project (Vite)
        run:  cd my-app && npx vite build

  docker:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Debug Working Directory
        run: pwd && ls -la
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          docker build -t nevereverfelix/my-vite-app:latest -f my-app/Dockerfile my-app
          docker tag nevereverfelix/my-vite-app:latest nevereverfelix/my-vite-app:${{ github.sha }}
          docker tag nevereverfelix/my-vite-app:latest nevereverfelix/my-vite-app:stable

      - name: Push Docker Image
        run: |
          docker push nevereverfelix/my-vite-app:latest
          docker push nevereverfelix/my-vite-app:${{ github.sha }}
          docker push nevereverfelix/my-vite-app:stable
      - name: Verify Image Exists
        run: docker images

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Pulling new image..."
            docker pull nevereverfelix/my-vite-app:latest

            echo "Starting new container..."
            docker run -d --name new_vite_app -p 80:80 nevereverfelix/my-vite-app:latest || (
              echo "Deployment failed! Rolling back to stable version..."
              docker pull nevereverfelix/my-vite-app:stable
              docker run -d --name new_vite_app -p 80:80 nevereverfelix/my-vite-app:stable
            )

            echo "Stopping old container..."
            docker stop beautiful_jang || true
            docker rm beautiful_jang || true
            echo "Renaming new container..."
            docker rename new_vite_app beautiful_jang